file_format: "1"
id: redox_manuform
name: Redox Manuform
type: shield
url: https://github.com/1770438260/Redox-Manuform
requires: [2 x nrfmicro_13]
features:
  - keys
  - wireless
  - split
siblings:
  - redox_manuform_left
  - redox_manuform_right
